# #####################################################################################################################
#
#
# #####################################################################################################################
# BOF
---

#######################################################################################################################
# Software package installs
# doc: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html
#######################################################################################################################
- name: Update package repository and cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600
#
- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: true
#
- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: false
  register: systemRebootRequired
#
- name: Reboot required after kernel update
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: systemRebootRequired.stat.exists
#
- name: Install package dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    #
    state: present
  with_items: "{{ InstallPackagesDependencies }}"
#
- name: Install packages
  ansible.builtin.apt:
    name: "{{ '%s' | format(item) }}"
    allow_downgrade: true
    #
    state: present
  with_items: "{{ InstallPackages }}"
#######################################################################################################################
#
#
#######################################################################################################################
#
# addgroup svn
# chown -R :svn /opt/svn/
# chmod 0771 /opt/svn/
#
# mkdir -p /opt/svn/repos/
# chown -R :svn /opt/svn/repos/
# chmod -R 2775 /opt/svn/repos/
#
# usermod -a -G svn dkp
# usermod -a -G svn sohraubpazuki
#
# umask 002
# svnadmin create /opt/svn/repos/testRepo
#
# touch /opt/svn/svnserve.sh

# !/bin/sh
# set the umask so files are group-writable
# umask 002
# call the 'real' svnserve, also passing in the default repo location
# exec /usr/bin/svnserve "$@" -r /opt/svn/repos

# cd /usr/bin
# mv svnserve svnserve.bin
# ln -s /opt/svn/bin/svnserve.sh svnserve
# mv svn svn.bin
# ln -s /opt/svn/bin/svn.sh svn

...
# #####################################################################################################################
# ---------------------------------------------------------------------------------------------------------------------
# #####################################################################################################################
# EOF
